# Generated by Django 5.2 on 2025-05-07 16:17

from django.db import migrations

def create_default_categories(apps, schema_editor):
    # Get the Category model
    Category = apps.get_model('backend', 'Category')
    
    # Define the preset categories we agreed upon
    default_categories = [
        {'name': 'wedding', 'description': 'Wedding gifts and registry items'},
        {'name': 'anniversary', 'description': 'Anniversary celebration gifts'},
        {'name': 'birthday', 'description': 'Birthday wishlist items'},
        {'name': 'graduation', 'description': 'Graduation celebration gifts'},
        {'name': 'christmas', 'description': 'Christmas and holiday season gifts'},
        {'name': 'other', 'description': 'Other occasions and miscellaneous items'},
    ]
    
    # Create the categories if they don't exist
    for category in default_categories:
        Category.objects.get_or_create(
            name=category['name'],
            defaults={'description': category['description']}
        )

def delete_default_categories(apps, schema_editor):
    # No need to delete the categories if the migration is reversed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_category_name_alter_wishlist_privacy'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, delete_default_categories),
    ]
