# Generated by Django 5.2 on 2025-05-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_create_default_categories'),
        ('backend', 'create_default_categories'),
    ]

    operations = [
    ]
