# Generated by Django 5.2 on 2025-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_item_image_url_alter_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('christmas', 'Christmas'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private - Only you can see'), ('shared', 'Shared - Only people with the link can see')], default='private', max_length=20),
        ),
    ]
